import { useEffect, useState } from 'react';
import { getAllCourses, createCourse } from '../../api/courseApi.js';
export default function ManageCourses(){
 const [courses,setCourses]=useState([]),[formData,setFormData]=useState({courseName:'',duration:'',totalSeats:'',minimumPercentage:'',applicationFee:''}),[message,setMessage]=useState(''),[submitting,setSubmitting]=useState(false);
 const fetchCourses=async()=>{try{const r=await getAllCourses();setCourses(r.data)}catch{setMessage('Failed to load courses')}}; useEffect(()=>{fetchCourses()},[]);
 const handleChange=e=>setFormData({...formData,[e.target.name]:e.target.value});
 const handleSubmit=async e=>{e.preventDefault();setMessage('');setSubmitting(true);try{await createCourse({courseName:formData.courseName,duration:parseInt(formData.duration),totalSeats:parseInt(formData.totalSeats),minimumPercentage:parseFloat(formData.minimumPercentage),applicationFee:parseFloat(formData.applicationFee)});setMessage('Course created successfully');setFormData({courseName:'',duration:'',totalSeats:'',minimumPercentage:'',applicationFee:''});fetchCourses()}catch(err){setMessage(err.response?.data?.message||'Failed to create course')}finally{setSubmitting(false)}};
 return <main className="app-page"><div className="page-container"><section className="dashboard-hero"><div><span className="page-eyebrow">Course management</span><h1 className="page-title">Programs & seats</h1><p className="page-subtitle">Create admission programs and monitor available seats.</p></div></section>
 {message&&<div className={`app-alert ${message.includes('success')?'app-alert-success':'app-alert-error'}`}><i className={`bi ${message.includes('success')?'bi-check-circle':'bi-exclamation-circle'}`}/>{message}</div>}
 <div className="manage-grid"><section className="panel-card sticky-form"><div className="panel-head"><div className="panel-icon"><i className="bi bi-plus-lg"/></div><div><h2>Create program</h2><p>Add a new course to the admission catalogue.</p></div></div><form onSubmit={handleSubmit}><label className="form-label">Program name</label><input className="form-control mb-3" name="courseName" value={formData.courseName} onChange={handleChange} placeholder="e.g. B.E. Computer Science" required/><div className="row g-3 mb-3"><div className="col-6"><label className="form-label">Duration</label><div className="input-suffix"><input className="form-control" name="duration" type="number" min="1" value={formData.duration} onChange={handleChange} required/><span>months</span></div></div><div className="col-6"><label className="form-label">Total seats</label><input className="form-control" name="totalSeats" type="number" min="1" value={formData.totalSeats} onChange={handleChange} required/></div></div><div className="row g-3 mb-4"><div className="col-6"><label className="form-label">Minimum 12th %</label><div className="input-suffix"><input className="form-control" name="minimumPercentage" type="number" min="0" max="100" step="0.01" value={formData.minimumPercentage} onChange={handleChange} required/><span>%</span></div></div><div className="col-6"><label className="form-label">Application fee</label><div className="input-prefix"><span>₹</span><input className="form-control" name="applicationFee" type="number" min="0" step="0.01" value={formData.applicationFee} onChange={handleChange} required/></div></div></div><button className="btn btn-primary w-100" disabled={submitting}>{submitting?'Creating...':'Create program'} <i className="bi bi-arrow-right ms-2"/></button></form></section>
 <section><div className="section-heading compact"><div><h2>Existing programs</h2><p>{courses.length} programs in the catalogue</p></div></div><div className="course-list">{courses.map(c=><article className="course-row" key={c.id}><div className="course-row-icon"><i className="bi bi-mortarboard"/></div><div className="course-row-main"><h3>{c.courseName}</h3><div className="course-row-meta"><span><i className="bi bi-clock"/> {c.duration} months</span><span><i className="bi bi-percent"/> {c.minimumPercentage}% eligibility</span><span><i className="bi bi-wallet2"/> ₹{c.applicationFee}</span></div></div><div className="seat-count"><strong>{c.availableSeats}</strong><span>of {c.totalSeats} seats</span><div className="seat-progress"><span style={{width:`${Math.max(0,Math.min(100,(c.availableSeats/c.totalSeats)*100))}%`}}/></div></div></article>)}</div></section></div>
 </div></main>}
